const actionTypes = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGGED_OUT: 'LOGGED_OUT',

  REQUEST_TODOS: 'REQUEST_TODOS',
  RECEIVE_TODOS: 'RECEIVE_TODOS',

  ADD_TODO: 'ADD_TODO',
  ADDED_TODO: 'ADDED_TODO',

  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLED_TODO: 'TOGGLED_TODO',

  DELETE_TODO: 'DELETE_TODO',
  DELETED_TODO: 'DELETED_TODO',

  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',

  SET_SEARCH_FILTER: 'SET_SEARCH_FILTER',

  LOADING: 'LOADING',

  SET_ERROR: 'SET_ERROR'
};

export default actionTypes;